language: node_js
node_js:
  - "10"
dist: trusty

before_script:
  - npm i

script:
  - npm run lint
  - npm run test
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage
